[Settings]
;
; Defines if language changer should use XML format (comment if not needed, "XMLElement" and "XMLChildElement" affected)
;
;UseXMLFormat = 1
;
; Defines if language changer should use INI format (comment if not needed, "INISection" and "INIKey" affected)
;
UseINIFormat = 1
;
; Defines the element of XML-like file to be read
;
;XMLElement = root
;
; Defines the child element of XML-like file to be read
;
;XMLChildElement = Language
;
; Defines the section of file to be read
;
INISection = Settings
;
; Defines the key of file to be read
;
INIKey = Language
;
; Defines the template for file to be changed
;
LanguageFileTemplate = steam_emu_t
;
; Defines the constant for a template language file
;
LanguageFileTemplateConstant = &LANG&
;
; Defines the file that needs to be changed
;
LanguageFile = steam_emu.ini
;
; Defines path to executable file to launch
;
ExeFile = s2_sp64_ship.exe
;
; Defines path to executable file to launch [x86]
;
ExeFile32 = s2_sp64_ship.exe